import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules';
import {execSync} from "child_process";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const copyFilePlugin = {
    name: 'copy-file',
    setup(build) {
        build.onEnd(result => {
            if(!result.errors.length) {
                execSync("cp ./main.js ./manifest.json ./styles.css ../../../BaiduSyncdisk/知识库/我的空间/.obsidian/plugins/export-image-test/");
            }
        });
    }
};

esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	watch: !prod,
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
    plugins:[copyFilePlugin]
}).catch(() => process.exit(1));
